### ISSUE TITLE
Getting user detected as spammer notice even if the user is very new.

### ISSUE THREAD

**Issue by gurjyot** [amiyasahu/q2a-registration-blocker#2]
I have just made a mail ID which not used before and I am getting his notice on registration.

"You are detected as a spammer and Not allowed to register here. If you got this accidentally then contact Administrator"

Beneath that it is saying... "This username is blocked, please chose some other username."

But the username is not blocked in admin section.

**Comment by amiyasahu** [comment]
Screenshot please

**Comment by amiyasahu** [comment]
removed the stopspamforum API and closing the bug
